name: serious_python_android
description: Android implementation of the serious_python plugin
homepage: https://flet.dev
repository: https://github.com/flet-dev/serious-python
version: 0.7.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  serious_python_platform_interface:
    path: ../serious_python_platform_interface
  path: ^1.9.0
  ffi: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^9.0.0
  
flutter:
  plugin:
    implements: serious_python
    platforms:
      android:
        package: com.flet.serious_python_android
        pluginClass: AndroidPlugin
        dartPluginClass: SeriousPythonAndroid
        ffiPlugin: true